pipeline:

  deploy_stage:
    image: codestation/drone-stack
    host: tcp://192.168.99.104:2376 
    stack_name: sonar-qube
    compose: stack.yml
    registry: https://index.docker.io/v1/
    meta_data:
      REPLICAS: 1