version: '3.2'

services:
  api:
    image: sonarqube:lts-alpine
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
        window: 30s
    ports:
      - "9000"